export const strings = {
  en: {
    nav_dashboard: "Dashboard", nav_learn: "Learn", nav_practice: "Practice", nav_keyboard_chart: "Keyboard Chart", nav_font_setup: "Font Setup", nav_mapping_validator: "Mapping Validator", nav_converter: "Converter", nav_test: "Typing Test", nav_exam: "Exam Mode", nav_review: "Review", nav_games: "Games", nav_statistics: "Statistics", nav_certificates: "Certificates", nav_profiles: "Profiles", nav_settings: "Settings",
    header_typing_language: "Typing:", header_layout: "Layout:",
    learn_title: "Learn to Type", learn_subtitle_en: "Structured English typing lessons.", learn_subtitle_hi: "Structured Hindi typing lessons.",
    learn_legacy_locked_title: "Lessons locked for this legacy layout", learn_legacy_locked_body: "Kruti Dev and Remington GAIL lessons unlock only after their key mappings are verified. No mappings are guessed. Set up the licensed font and verify the layout to enable lessons.",
    settings_subtitle: "Manage your preferences.", settings_legacy_section: "Legacy Hindi (Kruti Dev / Remington)", settings_legacy_desc: "Set up the licensed font, verify key mappings, and use the Beta converter.", settings_desktop_section: "Desktop App", settings_desktop_desc: "Windows packaging is built via the project build scripts and GitHub Actions.", settings_hindi_section: "Hindi Input", settings_physical_hints: "Show physical key hints", settings_normalization: "Unicode normalization",
    dash_welcome: "Welcome", dash_daily_goal: "Daily goal", dash_minutes: "min", dash_streak: "Streak", dash_days: "days", dash_continue: "Continue", dash_avg_wpm: "Avg WPM", dash_avg_accuracy: "Avg Accuracy", dash_best_wpm: "Best WPM", dash_lessons_done: "Lessons Done", dash_practiced_today: "Practiced Today", dash_english_progress: "English Progress", dash_hindi_progress: "Hindi Progress", dash_weekly_speed: "Weekly Speed", dash_weekly_accuracy: "Weekly Accuracy", dash_weakest_keys: "Weakest Keys", dash_start_lesson: "Start Lesson", dash_one_min_test: "1-Min Test", dash_exam_test: "Exam Test", dash_weak_keys: "Weak Keys", dash_keyboard_chart: "Keyboard Chart",
    practice_exercise: "Exercise", practice_of: "of", practice_restart: "Restart", practice_gross_wpm: "Gross WPM", practice_net_wpm: "Net WPM", practice_accuracy: "Accuracy", practice_errors: "Errors", practice_progress: "Progress", practice_input_mode: "Input mode", practice_windows_setup: "Windows setup instructions", practice_lesson_passed: "Lesson passed!", practice_lesson_retry: "Try again to pass this lesson.", practice_back_to_learn: "Back to Learn",
    session_progress: "Progress", session_time: "Time", session_time_left: "Time left", session_next: "Next", session_cancel: "Cancel", session_finish: "Finish",
    test_title: "Typing Test", test_subtitle: "Take a timed typing test.", test_language: "Language", test_passage: "Passage", test_words: "words", test_duration: "Duration", test_minutes: "min", test_target_wpm: "Target WPM", test_target_accuracy: "Target Accuracy", test_start: "Start Test", test_result_title: "Test Result", test_finished_early: "Finished early", test_result_pass: "Passed", test_result_fail: "Not passed", test_gross_wpm: "Gross WPM", test_net_wpm: "Net WPM", test_accuracy: "Accuracy", test_errors: "Errors", test_duration_used: "Duration", test_saved: "Result saved to your profile.", test_retry: "Retry", test_new: "New Test",
  },
  hi: {
    nav_dashboard: "डैशबोर्ड", nav_learn: "सीखें", nav_practice: "अभ्यास", nav_keyboard_chart: "कीबोर्ड चार्ट", nav_font_setup: "फ़ॉन्ट सेटअप", nav_mapping_validator: "मैपिंग वैलिडेटर", nav_converter: "कन्वर्टर", nav_test: "टाइपिंग टेस्ट", nav_exam: "परीक्षा मोड", nav_review: "समीक्षा", nav_games: "गेम", nav_statistics: "आंकड़े", nav_certificates: "प्रमाणपत्र", nav_profiles: "प्रोफ़ाइल", nav_settings: "सेटिंग्स",
    header_typing_language: "टाइपिंग:", header_layout: "लेआउट:",
    learn_title: "टाइप करना सीखें", learn_subtitle_en: "संरचित अंग्रेज़ी पाठ।", learn_subtitle_hi: "संरचित हिन्दी पाठ।",
    learn_legacy_locked_title: "इस लीगेसी लेआउट के पाठ लॉक हैं", learn_legacy_locked_body: "कृति देव और रेमिंगटन गेल के पाठ तभी खुलते हैं जब उनकी की मैपिंग सत्यापित हो। कोई मैपिंग अनुमान से नहीं भरी गई।",
    settings_subtitle: "अपनी पसंद प्रबंधित करें।", settings_legacy_section: "लीगेसी हिन्दी (कृति देव / रेमिंगटन)", settings_legacy_desc: "लाइसेंस फ़ॉन्ट सेट करें, मैपिंग सत्यापित करें।", settings_desktop_section: "डेस्कटॉप ऐप", settings_desktop_desc: "विंडोज़ पैकेजिंग बिल्ड स्क्रिप्ट से बनती है।", settings_hindi_section: "हिन्दी इनपुट", settings_physical_hints: "भौतिक की संकेत दिखाएं", settings_normalization: "यूनिकोड नॉर्मलाइज़ेशन",
    dash_welcome: "स्वागत है", dash_daily_goal: "दैनिक लक्ष्य", dash_minutes: "मिनट", dash_streak: "स्ट्रीक", dash_days: "दिन", dash_continue: "जारी रखें", dash_avg_wpm: "औसत WPM", dash_avg_accuracy: "औसत सटीकता", dash_best_wpm: "सर्वश्रेष्ठ WPM", dash_lessons_done: "पूर्ण पाठ", dash_practiced_today: "आज अभ्यास किया", dash_english_progress: "अंग्रेज़ी प्रगति", dash_hindi_progress: "हिन्दी प्रगति", dash_weekly_speed: "साप्ताहिक गति", dash_weekly_accuracy: "साप्ताहिक सटीकता", dash_weakest_keys: "सबसे कमज़ोर कुंजियाँ", dash_start_lesson: "पाठ शुरू करें", dash_one_min_test: "1-मिनट टेस्ट", dash_exam_test: "परीक्षा टेस्ट", dash_weak_keys: "कमज़ोर कुंजियाँ", dash_keyboard_chart: "कीबोर्ड चार्ट",
    practice_exercise: "अभ्यास", practice_of: "में से", practice_restart: "फिर से शुरू करें", practice_gross_wpm: "ग्रॉस WPM", practice_net_wpm: "नेट WPM", practice_accuracy: "सटीकता", practice_errors: "त्रुटियाँ", practice_progress: "प्रगति", practice_input_mode: "इनपुट मोड", practice_windows_setup: "विंडोज़ सेटअप निर्देश", practice_lesson_passed: "पाठ पास हो गया!", practice_lesson_retry: "पाठ पास करने के लिए फिर प्रयास करें।", practice_back_to_learn: "सीखें पर वापस जाएं",
    session_progress: "प्रगति", session_time: "समय", session_time_left: "शेष समय", session_next: "अगला", session_cancel: "रद्द करें", session_finish: "समाप्त करें",
    test_title: "टाइपिंग टेस्ट", test_subtitle: "एक समयबद्ध टाइपिंग टेस्ट लें।", test_language: "भाषा", test_passage: "अनुच्छेद", test_words: "शब्द", test_duration: "अवधि", test_minutes: "मिनट", test_target_wpm: "लक्ष्य WPM", test_target_accuracy: "लक्ष्य सटीकता", test_start: "टेस्ट शुरू करें", test_result_title: "टेस्ट परिणाम", test_finished_early: "जल्दी समाप्त", test_result_pass: "पास", test_result_fail: "अनुत्तीर्ण", test_gross_wpm: "ग्रॉस WPM", test_net_wpm: "नेट WPM", test_accuracy: "सटीकता", test_errors: "त्रुटियाँ", test_duration_used: "अवधि", test_saved: "परिणाम आपकी प्रोफ़ाइल में सहेजा गया।", test_retry: "पुनः प्रयास करें", test_new: "नया टेस्ट",
  },
} as const;
export type StringKey = keyof typeof strings.en;
export type InterfaceLang = keyof typeof strings;
